### ISSUE TITLE
Can not swipe to new slide which has distance is larger than 3 from old slide when list slide is larger than 6 elements

### ISSUE THREAD

**Issue by sondt1610** [BotDanny/react-stacked-center-carousel#6]
- I am using swipeTo(5) to swipe but can not swipe to slide has distance is larger than 3 from old slide 
![image](https://user-images.githubusercontent.com/33110100/166181232-d76f327a-b0ba-4336-9172-8ec0137384a0.png)
- Link demo: https://codesandbox.io/s/stacked-center-carousel-2uq596

**Comment by BotDanny** [comment]
Thanks for reporting the bug! I was very busy with school and internship so sorry for the delay. It is now fixed and I updated the code section on the demo page so that you can copy and paste that into a new file and start exploring immediately.

**Comment by sondt1610** [comment]
@BotDanny I see this bug is not fixed yet. Please take a look at my example in the codesandbox

**Comment by BotDanny** [comment]
@sondt1610 You need to update `react-stacked-center-carousel` to the latest version, namely 1.0.7 as of now.

**Comment by sondt1610** [comment]
@BotDanny That bug fixed but has new bug: When list data has ten items, then swipe to ninth item or tenth item => error. You can see detail at this codesandbox: 
https://codesandbox.io/s/stacked-center-carousel-latest-7qrkig?file=/src/App.js
![image](https://user-images.githubusercontent.com/33110100/173170548-c2fbadf7-e262-4c1f-a4ee-1d5165d13ded.png)

**Comment by BotDanny** [comment]
Sorry for that, I have fixed it now. It will probably be a good idea to add some tests but I'm too busy to do that in the foreseeable future.

**Comment by BotDanny** [comment]
Please update to the latest version of 1.0.8

**Comment by sondt1610** [comment]
@BotDanny Great, this bug fixed. Thank you for your support. I will test for you. If there are any bugs I will contact you
